<a href="https://colab.research.google.com/github/RaghavMaskara21/Machine-Learning/blob/main/10_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
from numpy.random import RandomState
import pandas as pd 
 
import os
 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
 
import nltk
import re
import string

In [2]:
from nltk.stem import WordNetLemmatizer
dataset_csv = pd.read_csv('spam.csv',encoding='latin-1')
 
rng = RandomState()
 
dataset_csv = dataset_csv.sample(frac=0.75, random_state=rng)
 
print(dataset_csv.shape)
dataset_csv.head(3)

(2786, 5)


v1                                                 v2  Unnamed: 2  \
1668  ham                        Yes..but they said its IT.,         NaN   
2755  ham                              We r outside already.         NaN   
2425  ham  Hey!!! I almost forgot ... Happy B-day babe ! ...         NaN   

     Unnamed: 3 Unnamed: 4  
1668        NaN        NaN  
2755        NaN        NaN  
2425        NaN        NaN

In [3]:
nltk.download('stopwords')
nltk.download('wordnet')
stopwords = nltk.corpus.stopwords.words('english')
lemmatizer = WordNetLemmatizer()
train_X = []
def train_cleaner(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    train_X.append(review)
val_X = []
def val_cleaner(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    val_X.append(review)
test_X = []
def test_cleaner(text):
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
    review = ' '.join(review)
    test_X.append(review)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [6]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(dataset_csv.v2,dataset_csv.v1, test_size= 0.25, random_state=0)
 
tf_idf = TfidfVectorizer()
 
X_train_tf = tf_idf.fit_transform(x_train)
 
X_train_tf = tf_idf.transform(x_train)
print("For Training set: n_samples: %d, n_features: %d" % X_train_tf.shape)
 
X_test_tf = tf_idf.transform(x_test)
print("For Test set: n_samples: %d, n_features: %d" % X_test_tf.shape)

For Training set: n_samples: 2089, n_features: 5030
For Test set: n_samples: 697, n_features: 5030


In [10]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler(with_mean=False)    
x_train= st_x.fit_transform(X_train_tf)    
x_test= st_x.transform(X_test_tf)
 
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)  
 
y_pred= classifier.predict(x_test)
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("KNN without PCA")


Confusion Matrix: 
[[597   0]
 [ 96   4]]

Classification Report: 


NameError: ignored

In [ ]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)
 
y_pred= classifier.predict(x_test)
 
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("SVM without PCA")

Confusion Matrix: 
[[19 27]
 [17 37]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.53      0.41      0.46        46
           1       0.58      0.69      0.63        54

    accuracy                           0.56       100
   macro avg       0.55      0.55      0.55       100
weighted avg       0.55      0.56      0.55       100

SVM without PCA


In [ ]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(x_train, y_train)
 
y_pred= classifier.predict(x_test)
 
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("Random Forest without PCA")

Confusion Matrix: 
[[25 21]
 [25 29]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.50      0.54      0.52        46
           1       0.58      0.54      0.56        54

    accuracy                           0.54       100
   macro avg       0.54      0.54      0.54       100
weighted avg       0.54      0.54      0.54       100

Random Forest without PCA


## With PCA

In [ ]:
from sklearn.decomposition import PCA  
from sklearn.decomposition import TruncatedSVD
clf = TruncatedSVD(50)
X_train = clf.fit_transform(x_train)
 
X_test = clf.fit_transform(x_test)
PCa = PCA (n_components = 1)  
   
X_train = PCa.fit_transform(X_train)  
X_test = PCa.transform(X_test)  
   
explained_variance = PCa.explained_variance_ratio_  


In [ ]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler(with_mean=False)    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)
 
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(X_train, y_train)  
 
y_pred= classifier.predict(X_test)
 
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("KNN with PCA")

Confusion Matrix: 
[[20 26]
 [22 32]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.48      0.43      0.45        46
           1       0.55      0.59      0.57        54

    accuracy                           0.52       100
   macro avg       0.51      0.51      0.51       100
weighted avg       0.52      0.52      0.52       100

KNN with PCA


In [ ]:
from sklearn.svm import SVC  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)
 
y_pred= classifier.predict(X_test)
 
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("SVM with PCA")

Confusion Matrix: 
[[ 0 46]
 [ 0 54]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.54      1.00      0.70        54

    accuracy                           0.54       100
   macro avg       0.27      0.50      0.35       100
weighted avg       0.29      0.54      0.38       100

SVM with PCA


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(X_train, y_train)
 
y_pred= classifier.predict(X_test)
 
cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)
print()
print("Classification Report: ")
print(classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred)))
print("Random Forest with PCA")

Confusion Matrix: 
[[19 27]
 [18 36]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.51      0.41      0.46        46
           1       0.57      0.67      0.62        54

    accuracy                           0.55       100
   macro avg       0.54      0.54      0.54       100
weighted avg       0.54      0.55      0.54       100

Random Forest with PCA
